spring:
  datasource:
    url: jdbc:postgresql://aws-1-ap-southeast-1.pooler.supabase.com:5432/postgres?sslmode=require
    username: postgres.spzeyjwkefsfpahhrvov
    password: INLB5pWou0hUqONJ
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate # Cloud DB는 validate 권장
    properties:
      hibernate:
        jdbc.time_zone: Asia/Seoul
    show-sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://spzeyjwkefsfpahhrvov.supabase.co/auth/v1

server:
  port: 8080
